---
abstract: 'Exclude files/directories for Version Control Systems'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: File::Find::Rule::VCS
name: File-Find-Rule-VCS
no_index:
  directory:
    - inc
    - t
requires:
  File::Find::Rule: 0.20
  perl: 5.005
version: 1.04
